### ISSUE TITLE
Poor documentation around service account requirements

### ISSUE THREAD

**Issue by gpuckettdg** [j-white/activemq-k8s-discovery#6]
If a service account is required for this library to work, that should be specified in the documentation and optionally created as a part of the k8s deployment. Otherwise, this is just a pretty paperweight.

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/REDACTED/pods?labelSelector=release%3Dnotfor-demopurposes. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods is forbidden: User "system:serviceaccount:REDACTED:default" cannot list resource "pods" in API group "" in the namespace "REDACTED".

**Comment by j-white** [comment]
Pretty paperweights are my specialty.
